CREATE TABLE [dbo].[EC_Product](
[ProductID_int] [int] NOT NULL,
[ProductTypeID_int] [int] NULL,
[TypeName_nvarchar] [nvarchar](200) NULL,
[ProductTitle_nvarchar] [nvarchar](300) NULL,
[ProductFileName_nvarchar] [nvarchar](300) NULL,
[ProductAliasName_nvarchar] [nvarchar](200) NULL,
[WebSiteID_smallint] [smallint] NOT NULL,
[PhotoBigSize_nvarchar] [nvarchar](100) NULL,
[PhotoSmallSize_nvarchar] [nvarchar](100) NULL,
[UPC_nvarchar] [nvarchar](72) NULL,
[ProductKeyID_nvarchar] [nvarchar](50) NULL,
[Code_nvarchar] [nvarchar](100) NULL,
[Avoirdupois_float] [float] NULL,
[SortOrder_int] [int] NULL,
[Recommend_bit] [bit] NULL,
[Discount_int] [float] NULL,
[IsDiscount_tinyint] [tinyint] NULL,
[Destine_int] [int] NULL,
[IsStopSale_bit] [bit] NULL,
[IsPhysical_bit] [bit] NULL,
[Unit_nvarchar] [nvarchar](50) NULL,
[IsSalability_bit] [bit] NULL,
[IsNewproduct_bit] [bit] NULL,
[IsLeftover_bit] [bit] NULL,
[IsSpecialOffer_bit] [bit] NULL,
[FlagUpdate_tinyint] [tinyint] NULL,
[ShortDes_nvarchar] [nvarchar](4000) NULL,
[ProductDescription_ntext] [nvarchar](max) NULL,
[LastUpdate_datetime] [datetime] NULL,
[IsFreeShipping_bit] [bit] NULL,
[CreateTime_datetime] [datetime] NULL,
[ShowType_nvarchar] [nvarchar](50) NULL,
[IsOperated_bit] [tinyint] NULL,
[QDWTemplateID_int] [int] NULL,
[IsEnable_bit] [bit] NULL,
[IsRepair_bit] [bit] NOT NULL,
[BarCodeType_nvarchar] [nvarchar](50) NULL,
[TakePhotoStatus_tinyint] [tinyint] NULL,
[VentureStatus_tinyint] [tinyint] NULL,
[KeyID_bigint] [bigint] NULL,
[ProductBrand_nvarchar] [nvarchar](50) NULL,
[QDWProductStatus_int] [int] NULL,
[IndexCode_nvarchar] [nvarchar](50) NULL,
[UserHobbyCount_int] [int] NULL,
[VideoCount_int] [int] NULL,
[EbayVentureStatus_tinyint] [tinyint] NULL,
[ProductImageFileName_nvarchar] [nvarchar](500) NULL,
[ProductScore_float] [numeric](12, 4) NULL,
[SaleStatus_nvarchar] [nvarchar](50) NULL,
[SaleStatusRemark_nvarchar] [nvarchar](1000) NULL,
[productdefaultimage_nvarchar] [nvarchar](200) NULL,
[productprice_money] [money] NULL,
[IsCoolNovelties_bit] [bit] NULL,
[IsLifeStyle_bit] [bit] NULL,
[dailydealendtime_datetime] [datetime] NULL,
[dailydealenabled_bit] [bit] NULL,
[HasStock_bit] [bit] NULL,
[UserVideoCount_int] [int] NULL,
[ImageCount_int] [int] NULL,
[UserImageCount_int] [int] NULL,
[UserCommentCount_int] [int] NULL,
[CommentScore_numeric] [numeric](9, 1) NULL,
[ProductPeculiarity_nvarchar] [nvarchar](4000) NULL,
[EntryPerson_nvarchar] [nvarchar](50) NULL,
[IsCreateive_tinyint] [tinyint] NULL,
[IsSupportCustomized_tinyint] [tinyint] NULL,
[HasVideo_bit] [bit] NULL,
[OriginalKeyWords_nvarchar] [nvarchar](500) NULL,
[IsWholeSale_bit] [bit] NULL,
[QDWCreateDateTime_datetime] [datetime] NULL,
[DeepProcess_int] [int] NULL,
[DeepProcessTemplateID_int] [int] NULL,
[ExcavateKeyWords_nvarchar] [nvarchar](500) NULL,
[IsOneSale_tinyint] [tinyint] NULL,
[IsAliExpress_tinyint] [tinyint] NULL,
[AliExpressUnit_nvarchar] [nvarchar](100) NULL,
[AliExpressPriceDes_ntext] [nvarchar](max) NULL,
[Ranking_float] [float] NULL,
[PricePercent_float] [float] NULL,
[HolidayIndexCodes_nvarchar] [nvarchar](2000) NULL,
[BoundNumber_int] [int] NULL,
[PackageWeight_float] [float] NULL,
[SuttleWeight_float] [float] NULL,
[InputType_tinyint] [tinyint] NULL,
[GiftCardNo_nvarchar] [nvarchar](50) NULL,
[QDWDiscountRate_int] [int] NULL,
[IsDiscountLoss5_bit] [tinyint] NULL,
[DHCode_nvarchar] [nvarchar](100) NULL,
[ProductBrandID_int] [int] NULL,
[DHNo_Nvarchar] [nvarchar](100) NULL,
[IsMultiChoice_tinyint] [tinyint] NULL,
[IsSpecialProduct_tinyint] [tinyint] NULL,
[LongTailKeyWord_nvarchar] [nvarchar](1000) NULL,
[LastAppTime_nvarchar] [nvarchar](50) NULL,
[IsQualityProduct_tinyint] [tinyint] NULL,
[IsHaveSaleRight_tinyint] [tinyint] NULL,
[IsClearance_tinyint] [tinyint] NULL,
[IsClearence_tinyint] [tinyint] NULL,
[IsRecommend_bit] [bit] NULL,
[IsRecommendEnable_bit] [bit] NULL,
[IdentifyPrior_tinyint] [tinyint] NULL,
[BusinessBrand_nvarchar] [nvarchar](50) NULL,
[AuctionProductPrice_money] [money] NULL,
[Identify_tinyint] [tinyint] NULL,
[IsAttachedHot_bit] [bit] NULL,
[IsAttachedNew_bit] [bit] NULL,
[ShowPosition_int] [int] NULL,
[PackageLength_float] [float] NULL,
[PackageWidth_float] [float] NULL,
[PackageHeight_float] [float] NULL,
[IsNonsuch_tinyint] [tinyint] NULL,
[IsReSale_tinyint] [tinyint] NOT NULL,
[DiffPrice_money] [money] NOT NULL,
[DropshippingPrice_money] [money] NOT NULL,
[DiffRate_float] [money] NOT NULL,
[ProductBusMarker_nvarchar] [nvarchar](200) NULL,
[WholeSaleStandardPrice_money] [money] NULL,
[ProductIsAgent_tinyint] [tinyint] NULL,
[IsDinoMall_tinyint] [tinyint] NULL,
[IsAverageSize_tinyint] [tinyint] NULL,
[IsTaoBao_tinyint] [tinyint] NULL,
[reviewsupdatetime_datetime] [datetime] NULL,
[reviews_int] [int] NULL,
[BusinessName_nvarchar] [nvarchar](200) NULL,
[VentureStatusNew_tinyint] [tinyint] NULL,
[ventureLevelNew_tinyint] [tinyint] NULL,
[Diggs_int] [int] NULL,
[StockCount_Int] [int] NULL,
 CONSTRAINT [PK_EC_PRODUCT] PRIMARY KEY CLUSTERED
(
[ProductID_int] ASC,
[WebSiteID_smallint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [uProductFileName] UNIQUE NONCLUSTERED
(
[ProductFileName_nvarchar] ASC,
[WebSiteID_smallint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [uProductkey] UNIQUE NONCLUSTERED
(
[ProductKeyID_nvarchar] ASC,
[WebSiteID_smallint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO 